export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS'; 
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_LOGOUT = 'AUTH_LOGOUT'; 

export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_THEME = 'DARK_THEME';

export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const TOGGLE_LIKE = 'TOGGLE_LIKE';

export const REFRESH_FEED = 'REFRESH_FEED';
export const FETCH_FEED = 'FETCH_FEED';
export const UPDATE_POST_COMMENT = 'UPDATE_POST_COMMENT';
export const FEED_SET_LOADING = 'FEED_SET_LOADING';

export const FETCH_SECTIONS = 'FETCH_SECTIONS';

export const CURRENT_USER_FETCH = 'CURRENT_USER_FETCH';
export const USER_SET_LOADING = 'USER_SET_LOADING';

export const PROFILE_SET_LOADING = 'PROFILE_SET_LOADING';
export const SET_PROFILE_USER_DATA = 'SET_PROFILE_USER_DATA';
export const SET_PROFILE_USER_POSTS = 'SET_PROFILE_USER_POSTS';

export const SET_HOME_LOADING = 'SET_HOME_LOADING';