# Generated by Django 3.2.8 on 2021-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211015_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(null=True, upload_to='images/userPic'),
        ),
    ]
