# Generated by Django 3.2.8 on 2021-10-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(null=True, upload_to='userPic'),
        ),
    ]
