# Generated by Django 3.2.8 on 2021-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211019_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPic',
            field=models.ImageField(null=True, upload_to='userPic/'),
        ),
    ]
