# Generated by Django 3.2.8 on 2021-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likeCount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postText',
        ),
        migrations.AlterField(
            model_name='post',
            name='postFile',
            field=models.FileField(null=True, upload_to='postFile'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionPic',
            field=models.ImageField(upload_to='sectionPic'),
        ),
    ]
