# Generated by Django 3.2.8 on 2021-10-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20211019_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postSection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='feed.section'),
        ),
    ]
