# Generated by Django 3.2.8 on 2021-10-17 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_like_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
